# Generated by Django 6.0.4 on 2026-06-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='max_salary',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='min_salary',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
