# Generated by Django 6.0.5 on 2026-06-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_candidate_max_salary_candidate_min_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='max_salary',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='min_salary',
            field=models.BigIntegerField(),
        ),
    ]
