# Generated by Django 6.0.5 on 2026-06-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_candidate_max_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='max_salary',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='min_salary',
        ),
    ]
