# Generated by Django 6.0.4 on 2026-06-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_candidate_country_candidate_job_catagry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='upload_image',
        ),
    ]
