# Generated by Django 6.0.4 on 2026-06-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_candidate_upload_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='state',
        ),
    ]
