# Generated by Django 6.0.4 on 2026-06-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_candidate_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='website',
            field=models.URLField(max_length=50),
        ),
    ]
