# Generated by Django 6.0.4 on 2026-06-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_candidate_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='website',
            field=models.URLField(max_length=150),
        ),
    ]
