# Generated by Django 6.0.4 on 2026-06-10 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_company_address_alter_company_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='company',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='company',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo_pic',
        ),
        migrations.RemoveField(
            model_name='company',
            name='state',
        ),
        migrations.AddField(
            model_name='company',
            name='company_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='company_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='company_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='company_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='company_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to='company_logo/'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.usermaster'),
        ),
    ]
